/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as DashboardRouteImport } from './routes/_Dashboard'
import { Route as DashboardIndexRouteImport } from './routes/_Dashboard.index'
import { Route as DashboardWorkRouteImport } from './routes/_Dashboard.work'
import { Route as DashboardDashRouteImport } from './routes/_Dashboard.dash'

const DashboardRoute = DashboardRouteImport.update({
  id: '/_Dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardIndexRoute = DashboardIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardWorkRoute = DashboardWorkRouteImport.update({
  id: '/work',
  path: '/work',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardDashRoute = DashboardDashRouteImport.update({
  id: '/dash',
  path: '/dash',
  getParentRoute: () => DashboardRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof DashboardIndexRoute
  '/dash': typeof DashboardDashRoute
  '/work': typeof DashboardWorkRoute
}
export interface FileRoutesByTo {
  '/dash': typeof DashboardDashRoute
  '/work': typeof DashboardWorkRoute
  '/': typeof DashboardIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_Dashboard': typeof DashboardRouteWithChildren
  '/_Dashboard/dash': typeof DashboardDashRoute
  '/_Dashboard/work': typeof DashboardWorkRoute
  '/_Dashboard/': typeof DashboardIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/dash' | '/work'
  fileRoutesByTo: FileRoutesByTo
  to: '/dash' | '/work' | '/'
  id:
    | '__root__'
    | '/_Dashboard'
    | '/_Dashboard/dash'
    | '/_Dashboard/work'
    | '/_Dashboard/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  DashboardRoute: typeof DashboardRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_Dashboard': {
      id: '/_Dashboard'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_Dashboard/': {
      id: '/_Dashboard/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof DashboardIndexRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/_Dashboard/work': {
      id: '/_Dashboard/work'
      path: '/work'
      fullPath: '/work'
      preLoaderRoute: typeof DashboardWorkRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/_Dashboard/dash': {
      id: '/_Dashboard/dash'
      path: '/dash'
      fullPath: '/dash'
      preLoaderRoute: typeof DashboardDashRouteImport
      parentRoute: typeof DashboardRoute
    }
  }
}

interface DashboardRouteChildren {
  DashboardDashRoute: typeof DashboardDashRoute
  DashboardWorkRoute: typeof DashboardWorkRoute
  DashboardIndexRoute: typeof DashboardIndexRoute
}

const DashboardRouteChildren: DashboardRouteChildren = {
  DashboardDashRoute: DashboardDashRoute,
  DashboardWorkRoute: DashboardWorkRoute,
  DashboardIndexRoute: DashboardIndexRoute,
}

const DashboardRouteWithChildren = DashboardRoute._addFileChildren(
  DashboardRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  DashboardRoute: DashboardRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
